insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Argentina','ARG',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Australia','AUS',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Brazil','BRA',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Canada','CAN',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('China','CHN',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('France','FRA',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Germany','DEU',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('India','IND',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Indonesia','IDN',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Iran','IRN',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Italy','ITA',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Japan','JPN',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Mexico','MEX',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Myanmar','MMR',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Pakistan','PAK',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Philippines','PHL',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Poland','POL',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Russia','RUS',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Africa','ZAF',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Korea','KOR',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Spain','ESP',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Turkey','TUR',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United States','USA',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Vietnam','VNM',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United Kingdom','GBR',2018);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Argentina','ARG',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Australia','AUS',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Brazil','BRA',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Canada','CAN',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('China','CHN',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('France','FRA',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Germany','DEU',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('India','IND',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Indonesia','IDN',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Iran','IRN',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Italy','ITA',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Japan','JPN',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Mexico','MEX',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Myanmar','MMR',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Pakistan','PAK',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Philippines','PHL',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Poland','POL',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Russia','RUS',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Africa','ZAF',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Korea','KOR',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Spain','ESP',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Turkey','TUR',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United States','USA',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Vietnam','VNM',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United Kingdom','GBR',2019);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Argentina','ARG',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Australia','AUS',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Brazil','BRA',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Canada','CAN',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('China','CHN',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('France','FRA',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Germany','DEU',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('India','IND',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Indonesia','IDN',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Iran','IRN',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Italy','ITA',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Japan','JPN',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Mexico','MEX',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Myanmar','MMR',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Pakistan','PAK',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Philippines','PHL',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Poland','POL',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Russia','RUS',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Africa','ZAF',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Korea','KOR',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Spain','ESP',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Turkey','TUR',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United States','USA',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Vietnam','VNM',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United Kingdom','GBR',2020);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Argentina','ARG',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Australia','AUS',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Brazil','BRA',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Canada','CAN',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('China','CHN',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('France','FRA',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Germany','DEU',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('India','IND',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Indonesia','IDN',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Iran','IRN',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Italy','ITA',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Japan','JPN',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Mexico','MEX',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Myanmar','MMR',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Pakistan','PAK',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Philippines','PHL',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Poland','POL',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Russia','RUS',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Africa','ZAF',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Korea','KOR',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Spain','ESP',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Turkey','TUR',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United States','USA',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Vietnam','VNM',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United Kingdom','GBR',2021);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Argentina','ARG',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Australia','AUS',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Brazil','BRA',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Canada','CAN',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('China','CHN',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('France','FRA',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Germany','DEU',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('India','IND',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Indonesia','IDN',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Iran','IRN',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Italy','ITA',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Japan','JPN',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Mexico','MEX',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Myanmar','MMR',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Pakistan','PAK',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Philippines','PHL',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Poland','POL',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Russia','RUS',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Africa','ZAF',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Korea','KOR',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Spain','ESP',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Turkey','TUR',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United States','USA',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Vietnam','VNM',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United Kingdom','GBR',2022);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Argentina','ARG',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Australia','AUS',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Brazil','BRA',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Canada','CAN',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('China','CHN',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('France','FRA',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Germany','DEU',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('India','IND',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Indonesia','IDN',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Iran','IRN',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Italy','ITA',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Japan','JPN',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Mexico','MEX',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Myanmar','MMR',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Pakistan','PAK',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Philippines','PHL',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Poland','POL',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Russia','RUS',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Africa','ZAF',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Korea','KOR',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Spain','ESP',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Turkey','TUR',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United States','USA',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Vietnam','VNM',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United Kingdom','GBR',2023);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Argentina','ARG',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Australia','AUS',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Brazil','BRA',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Canada','CAN',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('China','CHN',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('France','FRA',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Germany','DEU',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('India','IND',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Indonesia','IDN',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Iran','IRN',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Italy','ITA',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Japan','JPN',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Mexico','MEX',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Myanmar','MMR',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Pakistan','PAK',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Philippines','PHL',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Poland','POL',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Russia','RUS',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Africa','ZAF',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Korea','KOR',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Spain','ESP',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Turkey','TUR',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United States','USA',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Vietnam','VNM',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United Kingdom','GBR',2024);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Argentina','ARG',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Australia','AUS',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Brazil','BRA',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Canada','CAN',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('China','CHN',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('France','FRA',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Germany','DEU',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('India','IND',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Indonesia','IDN',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Iran','IRN',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Italy','ITA',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Japan','JPN',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Mexico','MEX',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Myanmar','MMR',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Pakistan','PAK',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Philippines','PHL',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Poland','POL',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Russia','RUS',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Africa','ZAF',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Korea','KOR',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Spain','ESP',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Turkey','TUR',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United States','USA',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Vietnam','VNM',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United Kingdom','GBR',2025);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Argentina','ARG',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Australia','AUS',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Brazil','BRA',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Canada','CAN',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('China','CHN',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('France','FRA',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Germany','DEU',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('India','IND',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Indonesia','IDN',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Iran','IRN',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Italy','ITA',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Japan','JPN',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Mexico','MEX',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Myanmar','MMR',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Pakistan','PAK',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Philippines','PHL',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Poland','POL',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Russia','RUS',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Africa','ZAF',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Korea','KOR',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Spain','ESP',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Turkey','TUR',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United States','USA',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Vietnam','VNM',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United Kingdom','GBR',2026);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Argentina','ARG',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Australia','AUS',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Brazil','BRA',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Canada','CAN',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('China','CHN',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('France','FRA',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Germany','DEU',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('India','IND',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Indonesia','IDN',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Iran','IRN',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Italy','ITA',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Japan','JPN',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Mexico','MEX',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Myanmar','MMR',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Pakistan','PAK',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Philippines','PHL',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Poland','POL',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Russia','RUS',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Africa','ZAF',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Korea','KOR',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Spain','ESP',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Turkey','TUR',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United States','USA',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Vietnam','VNM',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United Kingdom','GBR',2027);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Argentina','ARG',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Australia','AUS',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Brazil','BRA',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Canada','CAN',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('China','CHN',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('France','FRA',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Germany','DEU',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('India','IND',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Indonesia','IDN',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Iran','IRN',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Italy','ITA',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Japan','JPN',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Mexico','MEX',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Myanmar','MMR',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Pakistan','PAK',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Philippines','PHL',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Poland','POL',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Russia','RUS',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Africa','ZAF',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Korea','KOR',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Spain','ESP',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Turkey','TUR',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United States','USA',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Vietnam','VNM',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United Kingdom','GBR',2028);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Argentina','ARG',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Australia','AUS',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Brazil','BRA',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Canada','CAN',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('China','CHN',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('France','FRA',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Germany','DEU',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('India','IND',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Indonesia','IDN',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Iran','IRN',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Italy','ITA',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Japan','JPN',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Mexico','MEX',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Myanmar','MMR',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Pakistan','PAK',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Philippines','PHL',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Poland','POL',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Russia','RUS',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Africa','ZAF',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Korea','KOR',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Spain','ESP',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Turkey','TUR',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United States','USA',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Vietnam','VNM',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United Kingdom','GBR',2029);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Argentina','ARG',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Australia','AUS',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Brazil','BRA',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Canada','CAN',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('China','CHN',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('France','FRA',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Germany','DEU',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('India','IND',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Indonesia','IDN',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Iran','IRN',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Italy','ITA',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Japan','JPN',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Mexico','MEX',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Myanmar','MMR',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Pakistan','PAK',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Philippines','PHL',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Poland','POL',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Russia','RUS',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Africa','ZAF',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('South Korea','KOR',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Spain','ESP',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Turkey','TUR',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United States','USA',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('Vietnam','VNM',2030);
insert into EGS.top_25_meat_consumption (Entity,Code,Year) values ('United Kingdom','GBR',2030);

	alter table EGS.top_25_meat_consumption add COLUMN month VARCHAR(50);

alter table EGS.top_25_meat_consumption add COLUMN dates VARCHAR(100);

UPDATE EGS.top_25_meat_consumption
SET dates = CONCAT(month,'-',Year);

UPDATE EGS.top_25_meat_consumption
SET month = 'January';
